version: '3.1'

services:
  mongo-express:
    image: mongo
    ports:
      - 28017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_URL: mongodb://root:toor@mongo:27017/
    volumes:
      - ./mongo:/var/lib/postgresql/data